In [76]:
import numpy as np
import pandas as pd

In [77]:
df = pd.read_csv('/content/customer.csv')

In [78]:
df.sample(5)

age  gender   review education purchased
36   34  Female     Good        UG       Yes
15   75    Male     Poor        UG        No
21   32    Male  Average        PG        No
48   39  Female     Good        UG       Yes
3    72  Female     Good        PG        No

In [79]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [80]:
df = df.iloc[:,2:]

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[ :,0:2],df.iloc[ :,-1],test_size=0.2)

In [82]:
x_train

review education
24  Average        PG
7      Poor    School
39     Poor        PG
32  Average        UG
3      Good        PG
41     Good        PG
19     Poor        PG
18     Good    School
13  Average    School
34  Average    School
9      Good        UG
11     Good        UG
40     Good    School
30  Average        UG
42     Good        PG
26     Poor        PG
0   Average    School
44  Average        UG
15     Poor        UG
22     Poor        PG
47     Good        PG
23     Good    School
36     Good        UG
16     Poor        UG
4   Average        UG
14     Poor        PG
28     Poor    School
25     Good    School
43     Poor        PG
45     Poor        PG
31     Poor    School
48     Good        UG
37  Average        PG
10     Good        UG
46     Poor        PG
21  Average        PG
2      Good        PG
20  Average    School
1      Poor        UG
33     Good        PG

In [83]:
from sklearn.preprocessing import OrdinalEncoder

In [84]:
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

In [85]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [86]:
x_train=oe.transform(x_train)


In [87]:
x_test=oe.transform(x_test)

In [88]:
x_test

array([[0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.]])

In [89]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [90]:
x_train

array([[1., 2.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [2., 2.]])

In [92]:
from sklearn.preprocessing import LabelEncoder

In [93]:
le = LabelEncoder()

In [94]:
le.fit(y_train)

LabelEncoder()

In [95]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [96]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [97]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1])